# Generated by Django 2.2.1 on 2019-05-09 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
